name: 'CDN for pace'

on:
  push:
    branches: 
      - master

jobs:
  CDN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: 222e

